#========Database Datasource Connection===============
spring.application.name=springproject
spring.datasource.url=jdbc:mysql://localhost:3306/springproject?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

#===========Hibernate & JPA Config===========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true